ersion: '3.1'

services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video
    volumes:
      - ./config/:/etc/selenoid/ # assumed current dir contains browsers.json
      - ./video/:/opt/selenoid/video/
      - /var/run/docker.sock:/var/run/docker.sock

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]